export const CONFIGURATOR_SELECT_ITEM = 'CONFIGURATOR_SELECT_ITEM';
export const CONFIGURATOR_REMOVE_ITEM = 'CONFIGURATOR_REMOVE_ITEM';
export const CONFIGURATOR_SHOW_PROPERTIES = 'CONFIGURATOR_SHOW_PROPERTIES';
export const CONFIGURATOR_SET_FORM = 'CONFIGURATOR_SET_FORM';
export const CONFIGURATOR_SET_PAGES = 'CONFIGURATOR_SET_PAGES';
export const CONFIGURATOR_SET_GROUPS = 'CONFIGURATOR_SET_GROUPS';
export const CONFIGURATOR_SET_FIELDS = 'CONFIGURATOR_SET_FIELDS';

export const UI_SET_DIMENSIONS = 'UI_SET_DIMENSIONS';

export const FIELDS_SET_FIELD = 'FIELDS_SET_FIELD';
